name: zefa
path: '/vagrant/apps'
test: rspec
git: true

database: 
  adapter:  postgresql
  user:     postgres
  password: postgres

gems:
  groups:
    all:
      rails:       
        version: '3.2.12'
        #path:
        #github:
        #tag:
        #branch:
      haml:
    
    development-test:
      rspec-rails: 
  
