name: name_application
path: "/vagrant/apps"
test: rspec
git:
  gitignore: ["*.swo", "*.swp"]
  #repository: 'git@name_repository.com:user/name_application.git'
  #first_commit: true

database:
  adapter:  postgresql
  user:     postgres
  password: postgres

gems:
  groups:
    all:
      rails:
        version: '3.2.12'
        #path:
        #github:
        #tag:
        #branch:
      haml:

    assets:

    development:

    test:

    development_test:
      rspec-rails:

    production:
