name: name_application
path: '/vagrant/apps'
test: rspec
git: true
gitignore: ["*.swo", "*.swp"]

database:
  adapter:  postgresql
  user:     postgres
  password: postgres

gems:
  groups:
    all:
      rails:
        version: '3.2.12'
        #path:
        #github:
        #tag:
        #branch:
      haml:

    development:

    test:

    development_test:
      rspec-rails:
